### ISSUE TITLE
Could you please publish 1.2.4 and 1.3.0 to Maven Central?

### ISSUE THREAD

**Issue by aterweele** [iZettle/dropwizard-metrics-influxdb#101]
Hello! Like @eranharel I'm working on https://github.com/metrics-clojure/metrics-clojure/issues/133. I see tags for 1.2.4. and 1.3.0 but I do not see a release in https://mvnrepository.com/artifact/com.izettle/dropwizard-metrics-influxdb:

> Could not find artifact com.izettle:dropwizard-metrics-influxdb:jar:1.2.4 in central (https://repo1.maven.org/maven2/)

Thanks!

**Comment by otrosien** [comment]
ping.

**Comment by nivekuil** [comment]
Looks like 1.3.2 has been published https://mvnrepository.com/artifact/com.izettle/dropwizard-metrics-influxdb/1.3.2
