### ISSUE TITLE
Frequency in seconds

### ISSUE THREAD

**Issue by grzegorz-gn** [iZettle/dropwizard-metrics-influxdb#34]
Is it possible to set frequency in seconds.
For example to 30s

**Comment by xiaodong-izettle** [comment]
Of course, the default configuration is inherited from here: https://github.com/dropwizard/dropwizard/blob/master/dropwizard-metrics/src/main/java/io/dropwizard/metrics/MetricsFactory.java#L45

**Comment by grzegorz-gn** [comment]
Thanks for reply.

Yes, when frequency is set to 10 second - data is sending every 10 second to influx.
But when i check rows with data in Influx - new rows appear every 1 minute.

**Comment by xiaodong-izettle** [comment]
Ah, sorry for the misunderstanding, @grzegorz-gn. I think you need to tune the `precision` config item. :)

`precision: 1m # only store time precision to the minute`

**Comment by grzegorz-gn** [comment]
Thanks for advice.
It works.

**Comment by xiaodong-izettle** [comment]
Nice, and you're welcome. :)
