### ISSUE TITLE
TCP Support

### ISSUE THREAD

**Issue by shanielh** [iZettle/dropwizard-metrics-influxdb#38]
Telegraf now supports TCP listener with many formats ([Learn more about it](https://github.com/influxdata/telegraf/tree/master/plugins/inputs/tcp_listener)).

I would like to use the reporter to send messages to the Telegraf TCP Listener, so it will forward my messages to InfluxDB.

Can I add pull request for it?

**Comment by nzroller** [comment]
Sure go ahead @shanielh -- pull requests are welcome. We're trying to keep this library low on dependencies so if it's possible without any new dependencies that would be great.
