### ISSUE TITLE
UDP Support

### ISSUE THREAD

**Issue by z0mb1ek** [iZettle/dropwizard-metrics-influxdb#40]
Can i write to db by udp?

**Comment by shanielh** [comment]
I've just created a pull request (#39) that uses TCP connection to write to the database, I have no knowledge of the UDP listener, but if it uses the same line protocol as the TCP listener, I can make it work with UDP too.

**Comment by z0mb1ek** [comment]
can you read some docs https://docs.influxdata.com/influxdb/v0.12/write_protocols/udp/ ? =)

**Comment by shanielh** [comment]
> "To write, just send newline separated line protocol over UDP. For better performance send batches of points rather than multiple single points."

Seems like it uses the same protocol, I'll add it to my pull request.

**Comment by shanielh** [comment]
@z0mb1ek I've updated the pull request, it should address your problem too.

One thing I'm doing not quite right in the PR is getting the host name every time the UdpSender needs to report a batch of lines. I guess that if your computer does dns caching, it'll work great.

**Comment by z0mb1ek** [comment]
@shanielh big thx =) great job

**Comment by nzroller** [comment]
Implemented in #39 I believe.
