### ISSUE TITLE
Ability to tag individual metrics

### ISSUE THREAD

**Issue by DMarby** [iZettle/dropwizard-metrics-influxdb#42]
It would be great to be able to set tags for specific metrics, so that you can add dimensions on a per-metric basis.

**Comment by nzroller** [comment]
Yes that would be awesome! However this project was originally a stopgap solution while waiting for metrics v4 to be released which has a built-in [influx reporter](/dropwizard/metrics/tree/master/metrics-influxdb) which has support for per metric tags. It appears to not have a clear release plan though so it's unclear when that will be released.

I'll leave this open for if someone is willing to tackle it.

**Comment by bilyush** [comment]
Hi there. @nzroller, thanks a lot for the great library. I hope https://github.com/iZettle/dropwizard-metrics-influxdb/pull/67 will help with the issue

**Comment by rickard-von-essen-iz** [comment]
Fixed in #67
