### ISSUE TITLE
Spaces in tags return 400

### ISSUE THREAD

**Issue by nzroller** [iZettle/dropwizard-metrics-influxdb#45]
Using the latest released version it appears that spaces are no escaped in tags (or we should quote the tag values perhaps).

e.g. it appears we are sending this to influx:

client_connections,host=myhost,app=myservice,environment=dev,metricName=org.apache.http.conn.HttpClientConnectionManager.__My Service__ pending-connections=0.0,leased-connections=0.0,available-connections=0.0,max-connections=1024.0 24431578

and influx responds with a 400.

We should ensure that escaping on spaces is done on tags as well.

**Comment by ngong** [comment]
fixed, close
