### ISSUE TITLE
Auto create db

### ISSUE THREAD

**Issue by gurrie** [iZettle/dropwizard-metrics-influxdb#46]
Hi 

Could you please confirm whether it is possible to get the reporter to auto create the influxdb db?

Regards
Brian

**Comment by ngong** [comment]
Unfortunately no, not now. You have to create the db before sending data. But you got a good point, I will look into how to add this feature

**Comment by shanielh** [comment]
I guess it can be done easily when creating the reporter, In that case, You would also like to specify the wanted retention policy (w/ name).

I think I can manage to create a pull request for this. Maybe next week.

**Comment by gurrie** [comment]
That would be awesome!

**Comment by fredrikbackstrom** [comment]
I don't think that this is good idea. A write user shouldn't have access rights to create or alter the DB, so we shouldn't make that scenario easy to do wrong. 

There are also other aspects of migrations of the DB that doesn't fit nicely. Each database needs to grant access and set retention, these are things that can change and thus this need to handle db migrations, which I think is outside the scope of a reporter.

**Comment by rickard-von-essen-iz** [comment]
@fredrikbackstrom I agree with you.

Anyone opposing closing this as _wontfix_? @ngong @nzroller

**Comment by nzroller** [comment]
@rickard-von-essen-iz fine by me!

**Comment by ngong** [comment]
me as well

**Comment by rickard-von-essen-iz** [comment]
Closing this since we don't think it's good to support this. See https://github.com/iZettle/dropwizard-metrics-influxdb/issues/46#issuecomment-256322127.
