### ISSUE TITLE
Incorrect NaN handling

### ISSUE THREAD

**Issue by mmatloka** [iZettle/dropwizard-metrics-influxdb#47]
Hi,
I habe observed issue with handling NaNs. Some metrics can be reported with `Double.NaN` value, when such value goes through InfluxDbReporter it finially goes here https://github.com/iZettle/dropwizard-metrics-influxdb/blob/master/metrics-influxdb/src/main/java/com/izettle/metrics/influxdb/utils/InfluxDbWriteObjectSerializer.java#L66 

However `NumberFormat.getInstance(Locale.ENGLISH).format(Double.NaN).toCharArray()` is a `65533` (replacement character) and influx can not parse it and throws `400 Bad Request`. Influx also can not handle the `NaN` string (because then it does not know how to perform aggregations on such value). It seems that recommended method is to ommit metric with NaN value, so some checks are needed around creating fields maps https://github.com/iZettle/dropwizard-metrics-influxdb/blob/master/metrics-influxdb/src/main/java/com/izettle/metrics/influxdb/InfluxDbReporter.java#L334 so that NaN will never be added. 

I have also looked into not released dropwizard influxdb - it seems it is using json protocol instead of line protocol, where `The JSON write protocol is no longer a valid write protocol for InfluxDB.`  https://docs.influxdata.com/influxdb/v0.13/write_protocols/json/

**Comment by ngong** [comment]
Thank you for creating the issue. We will fix that later. BTW, we have already switched to line protocol in newer versions :)

**Comment by ngong** [comment]
Oh, just have seen the PR, nice job

**Comment by ngong** [comment]
PR merged, I will take a look at other Possible NaN and Inf in other number types.
Regards,
Nan (LOL, Yeah it is my name)

**Comment by mmatloka** [comment]
Thanks :)
