### ISSUE TITLE
Use line protocol

### ISSUE THREAD

**Issue by nzroller** [iZettle/dropwizard-metrics-influxdb#5]
The influxdb json protocol is deprecated and will be removed once v1 milestone is reached

**Comment by dkerwin** [comment]
Starting with 0.11.0 the JSON endpoint is disabled by default (see https://github.com/influxdata/influxdb/blob/v0.11.1/CHANGELOG.md#v0110-2016-03-22). PR #23 seems to address this issue already.

**Comment by DMarby** [comment]
Is there any idea when 1.1.3 which contains this will be uploaded to Maven central?

**Comment by nzroller** [comment]
@DMarby: we're doing internal testing to ensure it's stable for us. Hopefully today.

**Comment by DMarby** [comment]
@nzroller Awesome :) We've been running a bundled .jar in our pre-prod environment for a few days, and it seems to work fine

**Comment by nzroller** [comment]
Ah good to know @DMarby :-)

**Comment by nzroller** [comment]
We found an issue in the almost 1.1.3 release and made a `1.1.4` release instead which uses the line protocol, which should be available on maven central now.
