### ISSUE TITLE
Is prefix supported?

### ISSUE THREAD

**Issue by mrwilby** [iZettle/dropwizard-metrics-influxdb#50]
The InfluxDbReporterFactory class declares a prefix field and describes it as:

"The prefix for Metric key names to report to InfluxDb."

However, I don't see where this is used. 

We (would) use this to help organize our metrics namespace

**Comment by ngong** [comment]
No, not really, to clarify, it is the prefix of the measurement name. Is it what you need for your metrics namespace?

**Comment by mrwilby** [comment]
Yes, measurement name prefix. I branched the code to add support for this for now. Thanks

**Comment by ngong** [comment]
The problem is addressed on master branch. Will be included in next release. Close issue.
