### ISSUE TITLE
Please upgrade to dropwizard 1.0

### ISSUE THREAD

**Issue by mjwest10** [iZettle/dropwizard-metrics-influxdb#54]
Love using your library but we have recently updated to dropwizard 1.0 and it would be awesome if we could pull in a version of your library that matches.

**Comment by adamvoncorswant** [comment]
Hey @mjwest10 ! Yes, we've also started upgrading our services to 1.0: let's see if we can get some attention to this. BRB

**Comment by xiaodong-izettle** [comment]
Closed by #55
