### ISSUE TITLE
Remove parent in pom

### ISSUE THREAD

**Issue by fredrikbackstrom** [iZettle/dropwizard-metrics-influxdb#6]
Since public remove the parent reference? 

```
    <parent>
        <groupId>com.izettle</groupId>
        <artifactId>izettle</artifactId>
        <version>1.5</version>
    </parent>
```

**Comment by nzroller** [comment]
The base pom is public too, it's not deployed to maven central though. It aids in internal releases for now.

**Comment by nzroller** [comment]
BTW I'm open to this so long as the releases are straight-forward. (you have to manually set the altRepository somehow) if using the maven release plugin.

**Comment by fredrikbackstrom** [comment]
Ok, leave it for now. I want to remove izettle maven cause I don't really fancy it, but that may just be me.

**Comment by nzroller** [comment]
I agree we need to do something different for open-source projects. Planning on adding travis-ci for this project and this issue is a blocker.
