### ISSUE TITLE
Tag metrics with package, class, and method

### ISSUE THREAD

**Issue by rickard-von-essen-iz** [iZettle/dropwizard-metrics-influxdb#63]
Currently the metric `org.eclipse.jetty.util.thread.QueuedThreadPool.dw.utilization` will mapped to a measurement `thread_pools` with the tag `metricName:org.eclipse.jetty.util.thread.QueuedThreadPool.dw`:

It would be nice if it also resulted in the following tags:
- `package:org.eclipse.jetty.util.thread`
- `class:QueuedThreadPool`
- `method:dw`

These are very useful for nicer printouts.

**Comment by bilyush** [comment]
Hi @rickard-von-essen-iz, I saw couple of different use cases (aka how-to map metrics name to tags), e.g. https://github.com/davidB/metrics-influxdb/tree/master/src/main/java/metrics_influxdb/api/measurements

You can take a look at https://github.com/iZettle/dropwizard-metrics-influxdb/pull/67 ,probably that can help you to accomplish your request.
