### ISSUE TITLE
InfluxDbUdpSender ignores time precision and database

### ISSUE THREAD

**Issue by abadyan-vonage** [iZettle/dropwizard-metrics-influxdb#65]
The way Line Protocol works in influxdb, it assumes the time precision is in nanoseconds.
Database is determined by a binding in the server's config, directing the incoming packets to the correct db.
https://docs.influxdata.com/influxdb/v1.1/write_protocols/line_protocol_tutorial/

The fix here is pretty easy, do not accept precision and database as parameters and always pass nanoseconds as precision to the base client.
Database parameter should probably not be passed at all to the base client.

What is dangerous here is that if you don't notice it, you might spend 2 hours trying to figure out why time reporting is not working...

**Comment by z0mb1ek** [comment]
@ngong will you fix it please?

**Comment by rickard-von-essen-iz** [comment]
Closed in #68 and #69
